### ISSUE TITLE
Unable to install can't detect volume key

### ISSUE THREAD

**Issue by ghost** [pedrozzz0/King-Tweaks#11]
Wiko Power U20
Magisk: 26.1
Android 11
Stock Rom (Pure Android)
![Screenshot_20230701-105439](https://github.com/King-Projects/King-Tweaks/assets/131740614/c529a2ee-405a-4914-8dd6-b5ed3b0c1697)

[magisk_install_log_2023-07-01T10.54.28.log](https://github.com/King-Projects/King-Tweaks/files/11924360/magisk_install_log_2023-07-01T10.54.28.log)

**Comment by pedrozzz0** [comment]
This is outdated. Stick with latest version at https://t.me/kingprojectz
