### ISSUE TITLE
This will cause some VPN software to have no network, such as sagernet and anxiray

### ISSUE THREAD

**Issue by catbreast** [pedrozzz0/King-Tweaks#7]

**Comment by pedrozzz0** [comment]
hmmm, no kernel logs btw?

**Comment by catbreast** [comment]
KTSR_DBG.log

**Comment by catbreast** [comment]
https://github.com/SagerNet/SagerNet

**Comment by pedrozzz0** [comment]
so, after profile is applying? maybe something to do with tcp? can you provide me logcat / kernel logs to check it?

**Comment by pedrozzz0** [comment]
Will close the issue since is inactive. You can open again if you want to.
